"use client";
import { useState } from 'react';
import { Bookmark, ChevronRight, EyeOff, RotateCcw, Search } from 'lucide-react';
import { CopyContact } from '@/components/swarm/copy-contact';
import { ProviderLabels } from '@/components/swarm/provider-labels';
import { digits, type LeadRecord } from '@/lib/swarm/lead-book';

export function SavedBusinesses({ records, ready, open, restore }: { records: LeadRecord[]; ready: boolean; open: (key: string) => void; restore: (record: LeadRecord) => Promise<void> }) {
  const [tab, setTab] = useState<'saved' | 'hidden'>('saved');
  const [query, setQuery] = useState('');
  const [restoring, setRestoring] = useState('');
  const [error, setError] = useState('');
  const filtered = records.filter((r) => r.disposition === tab && `${r.card.business.name} ${r.card.business.address} ${digits(r.card.business.phone)} ${r.contactName} ${r.notes}`.toLowerCase().includes(query.toLowerCase())).sort((a,b) => b.updatedAt.localeCompare(a.updatedAt));
  async function undo(record: LeadRecord) { setRestoring(record.key); try { await restore(record); setError(''); } catch { setError('Could not restore the business. Please try again.'); } finally { setRestoring(''); } }
  return <div className="sw-saved-page"><div className="sw-result-heading"><div><span className="sw-overline">YOUR LEAD BOOK</span><h1>Saved businesses</h1><p>Full profiles, the people to ask for, and your notes.</p></div><Bookmark size={23}/></div><div className="sw-saved-toolbar"><div className="sw-tabs">{(['saved','hidden'] as const).map((key) => <button key={key} className={tab === key ? 'active' : ''} aria-pressed={tab === key} onClick={() => setTab(key)}>{key === 'saved' ? <Bookmark size={14}/> : <EyeOff size={14}/>} {key === 'saved' ? 'Saved' : 'Hidden'} <small>{records.filter(r => r.disposition === key).length}</small></button>)}</div><label className="sw-search"><Search size={15}/><input aria-label="Search saved businesses" placeholder="Search names, notes, or phone" value={query} onChange={(e) => setQuery(e.target.value)}/></label></div>{error && <p role="alert" className="sw-error">{error}</p>}<div className="sw-saved-list">{filtered.map((record) => <article key={record.key} className="sw-saved-card"><div className="sw-saved-card-top"><div><span className="sw-category-label">{record.card.business.category}</span><button className="sw-saved-name" onClick={() => open(record.key)}>{record.card.business.name}<ChevronRight size={17}/></button></div>{tab === 'hidden' && <button className="sw-secondary" disabled={restoring === record.key} onClick={() => void undo(record)}><RotateCcw size={13}/>Restore to saved</button>}</div><div className="sw-saved-contacts"><CopyContact label="address" value={record.card.business.address}/>{digits(record.card.business.phone) && <CopyContact label="phone number" value={digits(record.card.business.phone)}/>}</div>{record.contactName && <p className="sw-saved-contact-name">Ask for <strong>{record.contactName}</strong></p>}<p className="sw-saved-note">{record.notes || 'No notes yet. Open this business to add them.'}</p><div className="sw-saved-card-bottom"><ProviderLabels providers={record.card.broadband?.observations.map(o => o.provider) ?? []}/><button onClick={() => open(record.key)}>Edit notes <ChevronRight size={13}/></button></div></article>)}</div>{!filtered.length && <p className="sw-empty">{!ready ? 'Loading your lead book…' : query ? 'No businesses match this search.' : tab === 'saved' ? 'Save a business from its profile to keep it here with your notes.' : 'Businesses you hide will be kept out of Swarm results.'}</p>}<p className="sw-data-note">Stored in this browser on this device, including the full profile. Hidden businesses stay out of Swarm results, maps, routes, and exports.</p></div>;
}
