"use client";
import { useState } from "react";
import { AnimatePresence, motion } from "motion/react";
import { ArrowUpRight, Check, Copy, Globe, MapPin, Phone, Search, Star, Wifi, X, LoaderCircle, Building2, ExternalLink } from "lucide-react";
import { SwarmDialog } from "@/components/swarm/swarm-dialog";
import { prospectTalkingPoints, prospectCallOpener } from "@/lib/prospect-talking-points";
import type { SwarmBatch, SwarmProspect } from "@/lib/swarm/types";
function safeUrl(value: string | null) { try { const url = new URL(value ?? ''); return ['http:', 'https:'].includes(url.protocol) ? url.href : undefined; } catch { return undefined; } }
export function SwarmDetail({ card, batch, close, research, pending = false }: { card: SwarmProspect; batch: SwarmBatch; close: () => void; research: () => void; pending?: boolean }) {
  const [tab, setTab] = useState<'overview' | 'research' | 'sources'>('overview');
  const [copied, setCopied] = useState('');
  const p = card.business;
  const points = prospectTalkingPoints(p, card.intelligence);
  const opener = prospectCallOpener(p);
  const facts = card.intelligence?.facts ?? [];
  const highlights = facts.filter((fact) => ['leadership', 'founded', 'team_size', 'email'].includes(fact.kind)).slice(0, 5);
  const providers = [...new Set(card.broadband?.observations.map((item) => item.provider))];
  const researching = ['queued', 'researching'].includes(card.researchStatus);
  const directions = `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(p.address)}&travelmode=driving`;
  async function copy(text: string, label: string) { try { await navigator.clipboard.writeText(text); setCopied(`${label} copied`); } catch { setCopied('Clipboard unavailable in this browser.'); } }
  return <SwarmDialog label={p.name} close={close} className="sw-profile-modal">
    <header className="sw-profile-header">
      <div className="sw-modal-topline"><span><Building2 size={14}/> Prospect profile</span><button className="sw-icon" aria-label="Close profile" onClick={close}><X size={20}/></button></div>
      <div className="sw-profile-identity"><div className="sw-monogram" aria-hidden="true">{p.name.split(/\s+/).slice(0, 2).map((word) => word[0]).join('')}</div><div><span className="sw-profile-category">{p.category}</span><h2>{p.name}</h2><p><MapPin size={13}/>{p.address}</p></div></div>
      <div className="sw-profile-actions">{p.phone && <a href={`tel:${p.phone.replace(/[^+\d]/g, '')}`}><Phone size={14}/>{p.phone}</a>}{safeUrl(p.website) && <a href={safeUrl(p.website)} target="_blank" rel="noreferrer"><Globe size={14}/>Website<ArrowUpRight size={12}/></a>}<a href={directions} target="_blank" rel="noreferrer"><MapPin size={14}/>Directions</a><button className="sw-research-cta" disabled={researching || pending} onClick={research}>{researching ? <LoaderCircle className="sw-spin" size={14}/> : <Search size={14}/>} {researching ? 'Researching' : card.intelligence ? 'Refresh research' : 'Research business'}</button></div>
      <div className="sw-profile-tabs">{(['overview', 'research', 'sources'] as const).map((key) => <button key={key} aria-pressed={tab === key} onClick={() => setTab(key)}>{key === 'overview' ? 'Overview' : key === 'research' ? 'Research' : 'Sources & discovery'}{key === 'research' && facts.length > 0 && <small>{facts.length}</small>}{tab === key && <motion.span layoutId="profile-tab" transition={{ type: 'spring', stiffness: 380, damping: 34 }}/>}</button>)}</div>
    </header>
    <div className="sw-profile-body"><AnimatePresence mode="wait" initial={false}><motion.div key={tab} initial={{ opacity: 0, y: 5 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -3 }} transition={{ duration: .15 }}>
      {tab === 'overview' ? <div className="sw-profile-grid"><div className="sw-profile-main">
        <section><h3>The business</h3><p className="sw-profile-summary">{card.intelligence?.summary || p.publicNotes || `Listed as ${p.category.toLowerCase()}. Research this business to build a fuller picture before reaching out.`}</p><div className="sw-listing-metrics">{p.rating != null && <span><Star size={13}/><strong>{p.rating}</strong>{p.reviewCount != null ? ` · ${p.reviewCount} reviews` : ' listing rating'}</span>}{p.locationCount != null && <span><Building2 size={13}/>{p.locationCount} {p.locationCount === 1 ? 'location' : 'locations'}</span>}{p.operatingStatus !== 'Unknown' && <span className={p.operatingStatus === 'Open' ? 'sw-positive' : ''}>{p.operatingStatus === 'Open' ? 'Listed operational' : p.operatingStatus}</span>}</div>
          {highlights.length > 0 && <dl className="sw-highlight-facts">{highlights.map((fact) => <div key={fact.id}><dt>{fact.label}</dt><dd>{fact.value}{safeUrl(fact.sourceUrl) && <a href={safeUrl(fact.sourceUrl)} target="_blank" rel="noreferrer" aria-label={`Source for ${fact.label}`}><ArrowUpRight size={12}/></a>}</dd></div>)}</dl>}
        </section>
        <section className="sw-opener-section"><div className="sw-section-heading"><h3>A way to open</h3><button className="sw-icon" aria-label="Copy opening line" onClick={() => void copy(opener, 'Opening line')}><Copy size={14}/></button></div><blockquote>{opener}</blockquote><small>Make it yours before you call.</small></section>
        <section><h3>Worth asking</h3><ol className="sw-talking-points">{points.map((point, index) => <motion.li key={point} initial={{ opacity: 0, y: 4 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .035 }}><span>{String(index + 1).padStart(2, '0')}</span><p>{point}</p></motion.li>)}</ol></section>
      </div><aside className="sw-profile-context">
        <section className="sw-opportunity-box"><div className="sw-section-heading"><h3>Opportunity</h3><span className={`sw-status ${card.opportunity}`}>{card.opportunity === 'high' ? 'High priority' : card.opportunity === 'contact_needed' ? 'Find contact' : 'Review'}</span></div><div className="sw-profile-score"><strong>{card.rank}</strong><span>/ 100<br/>prospecting rank</span></div><ul>{card.reasons.map((reason) => <li key={reason}><Check size={13}/>{reason}</li>)}</ul></section>
        <section className="sw-broadband-box"><h3><Wifi size={15}/> Broadband availability</h3>{providers.length ? <div className="sw-provider-list">{providers.map((provider) => { const observations = card.broadband!.observations.filter((o) => o.provider === provider); const speeds = observations.map((o) => o.downloadMbps).filter((n): n is number => n != null && Number.isFinite(n)); return <div key={provider}><strong>{provider}</strong><span>{[...new Set(observations.map((o) => o.technology))].join(' · ')}{speeds.length ? ` · Up to ${Math.max(...speeds).toLocaleString()} Mbps down` : ''}</span></div>; })}</div> : <p>{card.broadbandChecked ? 'No provider availability confirmed.' : 'Availability check queued.'}</p>}<small>{card.broadband?.asOfDate ? `Reported ${card.broadband.asOfDate} · ${card.broadband.matchQuality.replaceAll('_', ' ')} match` : card.broadband?.message}</small><p className="sw-evidence-note">Current ISP is unverified. Availability does not confirm a subscription or orderability.</p></section>
        {p.hours?.length ? <section><h3>Listed hours</h3><ul className="sw-hours">{p.hours.map((hours, index) => <li key={index}>{hours}</li>)}</ul></section> : null}
      </aside></div> : tab === 'research' ? <section className="sw-research-facts"><div className="sw-section-heading"><div><h3>Public business research</h3><p>{facts.length ? 'Evidence you can trace back to its source.' : 'Add more context before your first conversation.'}</p></div>{researching && <LoaderCircle size={18} className="sw-spin"/>}</div>{facts.length ? facts.map((fact) => <div className="sw-fact" key={fact.id}><div><span>{fact.label}</span><small>{fact.confidence}</small></div><p>{fact.value}</p>{safeUrl(fact.sourceUrl) && <a href={safeUrl(fact.sourceUrl)} target="_blank" rel="noreferrer">{fact.sourceLabel || 'View source'}<ArrowUpRight size={12}/></a>}</div>) : <div className="sw-research-empty"><Search size={24}/><p>Research adds public company details, published leadership, and professional sources when available.</p><button className="sw-primary" disabled={researching || pending} onClick={research}>{researching ? 'Researching…' : 'Research business'}</button></div>}</section> : <div className="sw-source-grid"><section><h3>Evidence sources</h3>{safeUrl(p.directoryUrl) && <a className="sw-source-link" href={safeUrl(p.directoryUrl)} target="_blank" rel="noreferrer"><ExternalLink size={15}/><div><strong>{p.source || 'Business listing'}</strong><small>{p.confidence} · Retrieved {new Date(p.retrievedAt).toLocaleDateString()}</small></div><ArrowUpRight size={14}/></a>}{card.intelligence?.sources.map((source) => safeUrl(source.url) ? <a key={source.id} className="sw-source-link" href={safeUrl(source.url)} target="_blank" rel="noreferrer"><Globe size={15}/><div><strong>{source.label}</strong><small>{source.status} · {source.sourceDate}</small></div><ArrowUpRight size={14}/></a> : null)}{safeUrl(card.broadband?.sourceUrl ?? null) && <a className="sw-source-link" href={safeUrl(card.broadband!.sourceUrl)} target="_blank" rel="noreferrer"><Wifi size={15}/><div><strong>Broadband availability</strong><small>Reported {card.broadband?.asOfDate}</small></div><ArrowUpRight size={14}/></a>}</section><section><h3>Found from {card.sourceAddressIds.length} {card.sourceAddressIds.length === 1 ? 'address' : 'addresses'}</h3><p className="sw-evidence-note">One prospect, even when multiple searches found it.</p><ul className="sw-discovery-addresses">{card.sourceAddressIds.map((id) => <li key={id}><MapPin size={14}/>{batch.addresses.find((a) => a.id === id)?.text}</li>)}</ul></section></div>}
    </motion.div></AnimatePresence>{card.error && <p className="sw-error">{card.error}</p>}</div>
    <footer className="sw-modal-footer"><span role="status">{copied || `Updated ${new Date(card.updatedAt).toLocaleString()}`}</span><button className="sw-secondary" onClick={() => void copy(`${p.name}\n${p.address}\n${p.phone || ''}\n${card.intelligence?.summary || p.publicNotes || ''}\n\nOpening line\n${opener}\n\nQuestions\n${points.map((point) => `• ${point}`).join('\n')}`, 'Brief')}><Copy size={14}/>Copy brief</button></footer>
  </SwarmDialog>;
}
